---
output:
  md_document:
    variant: markdown_github
---


```{r}
load('data_PCA_E7.RData')
summary(X)
```
```{r}
x.pca<-prcomp(X)
print(x.pca)
plot(x.pca,type='l')
print(summary(x.pca))
```
```{r}
#z-score standardization
x.pca <- prcomp(X,center=TRUE,scale=TRUE)
print(x.pca)
plot(x.pca,type='l')
print(summary(x.pca))
```
#NN without PCA
```{r}
library(nnet)
rm(X)
rm(y)
load('data_NN_E7.RData')
summary(X)
```
```{r}
#min-max scaling

minx=apply(X,2,min)
maxx=apply(X,2,max)

miny=min(y)
maxy=max(y)

X_S=scale(X,minx,maxx-minx)
y_s=scale(y,miny,maxy-miny)
```

```{r}
# NN model
model_nn <- nnet(X_S, y_s, size=20,
                 maxit=300, decay=0.03, linout=TRUE, reltol=1.e-6, MaxNWts=100000)
```
```{r}
# produce the predictions
y_s.predict <- predict(model_nn, X_S)
print(cor(y_s.predict,y_s))
str(X)
```
# NN with PCA
```{r}
# remove binary variables and standardize X

miny=min(y)
maxy=max(y)
y_s=scale(y,miny,maxy-miny)

x.pca <- prcomp(X[,c(1,2,4,5,6,7,8)],center=TRUE,scale=TRUE)
pred_pca <- predict(x.pca)

print(pred_pca[1:5,])
print(summary(x.pca))
```

```{r}
# binary variables are added back to the data

N=7
x_data <- data.frame(X[,c(3,9,10)],pred_pca[,1:N])

```

```{r}
# NN model with pca

model_pcann <- nnet(x_data, y_s, size=20,
                 maxit=300, decay=0.03, linout=TRUE, reltol=1.e-6, MaxNWts=100000)
```
```{r}
# predict and eval
y_s.pred <- predict(model_pcann, x_data)
print(cor(y_s.pred, y_s))

```

```{r}
plot(y_s.pred,y_s)
```